/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Data.User;
import javax.swing.JOptionPane;

/**
 *
 * @author redouane
 */
public class ModifMotPasse extends javax.swing.JDialog {
    private static ModifMotPasse singleton = null;

    public static ModifMotPasse getSingleton() {
        if (singleton == null){
            singleton = new ModifMotPasse();
        }
        
        return singleton;
    }
    
    public static void showModifMotPasse(){
        getSingleton();
        
        singleton.emptyFields();
        singleton.setLocationRelativeTo(null);
        
        singleton.setVisible(true);
    }
    
    /**
     * Creates new form ModifMotPasse
     */
    private ModifMotPasse() {
        super(LogIn.getSingleton(), true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNomUtilisateur = new javax.swing.JTextField();
        pwfMotDePasse = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pwdNewPassword1 = new javax.swing.JPasswordField();
        pwdNewPassword2 = new javax.swing.JPasswordField();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGO.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), null));

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modifier son mot de passe");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Nom d'utilisateur");

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("Mots de Passe Actuel");

        tfNomUtilisateur.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        tfNomUtilisateur.setBorder(null);
        tfNomUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNomUtilisateurMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfNomUtilisateurMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNomUtilisateurMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomUtilisateurMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomUtilisateurMouseEntered(evt);
            }
        });

        pwfMotDePasse.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        pwfMotDePasse.setBorder(null);
        pwfMotDePasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwfMotDePasseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwfMotDePasseMouseClicked(evt);
            }
        });
        pwfMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfMotDePasseActionPerformed(evt);
            }
        });
        pwfMotDePasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwfMotDePasseKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfMotDePasseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwfMotDePasseKeyReleased(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/if_check_1930264.png"))); // NOI18N
        jButton1.setText("Modifier");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/if_Remove_27874.png"))); // NOI18N
        jButton2.setText("Annuler");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouveau mot de Passe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Nouveau mot de Passe : ");

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("Confirmer le mot de passe : ");

        pwdNewPassword1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        pwdNewPassword1.setBorder(null);
        pwdNewPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwdNewPassword1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdNewPassword1MouseClicked(evt);
            }
        });
        pwdNewPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdNewPassword1ActionPerformed(evt);
            }
        });
        pwdNewPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdNewPassword1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdNewPassword1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdNewPassword1KeyReleased(evt);
            }
        });

        pwdNewPassword2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        pwdNewPassword2.setBorder(null);
        pwdNewPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwdNewPassword2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdNewPassword2MouseClicked(evt);
            }
        });
        pwdNewPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdNewPassword2ActionPerformed(evt);
            }
        });
        pwdNewPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdNewPassword2KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdNewPassword2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdNewPassword2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdNewPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdNewPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwfMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(tfNomUtilisateur, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwfMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered

    }//GEN-LAST:event_jLabel7MouseEntered

    private void tfNomUtilisateurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomUtilisateurMousePressed
        jSeparator1.setBackground(java.awt.Color.red);
        jSeparator2.setBackground(java.awt.Color.white);

        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomUtilisateurMousePressed

    private void tfNomUtilisateurMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomUtilisateurMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomUtilisateurMouseReleased

    private void tfNomUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomUtilisateurMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomUtilisateurMouseClicked

    private void tfNomUtilisateurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomUtilisateurMouseExited
        jSeparator2.setBackground(java.awt.Color.red);
        jSeparator1.setBackground(java.awt.Color.white);           // TODO add your handling code here:
    }//GEN-LAST:event_tfNomUtilisateurMouseExited

    private void tfNomUtilisateurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomUtilisateurMouseEntered
        jSeparator1.setBackground(java.awt.Color.red);
        jSeparator2.setBackground(java.awt.Color.white);           // TODO add your handling code here:
    }//GEN-LAST:event_tfNomUtilisateurMouseEntered

    private void pwfMotDePasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwfMotDePasseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfMotDePasseMouseClicked

    private void pwfMotDePasseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwfMotDePasseMousePressed
        //  jSeparator2.setBackground(Color.RED);
        //jSeparator1.setBackground(Color.white);

        // TODO add your handling code here:
    }//GEN-LAST:event_pwfMotDePasseMousePressed

    private void pwfMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfMotDePasseActionPerformed

    private void pwfMotDePasseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfMotDePasseKeyPressed

    }//GEN-LAST:event_pwfMotDePasseKeyPressed

    private void pwfMotDePasseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfMotDePasseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfMotDePasseKeyReleased

    private void pwfMotDePasseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfMotDePasseKeyTyped

    }//GEN-LAST:event_pwfMotDePasseKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = this.tfNomUtilisateur.getText();
        String password = this.pwfMotDePasse.getText();
        String newpassword1 = this.pwdNewPassword1.getText();
        String newpassword2 = this.pwdNewPassword2.getText();
        
        if (username.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir le champs 'Nom d'utilisateur'...");
            tfNomUtilisateur.requestFocus();
            return;
        }
        
        if (password.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir le champs 'Mot de passe'...");
            pwfMotDePasse.requestFocus();
            return;
        }
        
        if (newpassword1.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir le champs 'Nouveau mot de passe'...");
            pwdNewPassword1.requestFocus();
            return;
        }
        
        if (newpassword2.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir le champs 'Confirmation mot de passe'...");
            pwdNewPassword2.requestFocus();
            return;
        }
        
        if (!newpassword1.equals(newpassword2)){
            JOptionPane.showMessageDialog(null, "Les deux mots de passe ne sont pas identique ....");
            pwdNewPassword1.requestFocus();            
            return;
        }
        
        User user =  User.logIn2(username, password);
        if (user == null){
            JOptionPane.showMessageDialog(null, "Erreur de nom d'utilisateur ou de mot de passe ...");
            tfNomUtilisateur.requestFocus();
            return;
        }
        
        user.setPassword( utils.MD5.getMd5( newpassword1 ) );
        try {
            user.Modifier();
        } catch (Exception e) {
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pwdNewPassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdNewPassword1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword1MousePressed

    private void pwdNewPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdNewPassword1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword1MouseClicked

    private void pwdNewPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdNewPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword1ActionPerformed

    private void pwdNewPassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPassword1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword1KeyTyped

    private void pwdNewPassword1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPassword1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword1KeyPressed

    private void pwdNewPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPassword1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword1KeyReleased

    private void pwdNewPassword2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdNewPassword2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword2MousePressed

    private void pwdNewPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdNewPassword2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword2MouseClicked

    private void pwdNewPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdNewPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword2ActionPerformed

    private void pwdNewPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPassword2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword2KeyTyped

    private void pwdNewPassword2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPassword2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword2KeyPressed

    private void pwdNewPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPassword2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdNewPassword2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifMotPasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifMotPasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifMotPasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifMotPasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifMotPasse().setVisible(true);
            }
        });
    }
    
    private void emptyFields(){
        this.tfNomUtilisateur.setText("");
        this.pwfMotDePasse.setText("");
        this.pwdNewPassword1.setText("");
        this.pwdNewPassword2.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField pwdNewPassword1;
    private javax.swing.JPasswordField pwdNewPassword2;
    private javax.swing.JPasswordField pwfMotDePasse;
    private javax.swing.JTextField tfNomUtilisateur;
    // End of variables declaration//GEN-END:variables
}
